/* The variants, by name, each loaded only when chosen. A variant is a module whose default export
   is make(layer, m); see the README. Adding one is adding its file and its line here. */
export var variants = {
  bats: function () { return import('./variants/bats.js'); },
  blockpeek: function () { return import('./variants/blockpeek.js'); },
  boids: function () { return import('./variants/boids.js'); },
  bytecode: function () { return import('./variants/bytecode.js'); },
  chase: function () { return import('./variants/chase.js'); },
  circuit: function () { return import('./variants/circuit.js'); },
  citydefense: function () { return import('./variants/citydefense.js'); },
  deadline: function () { return import('./variants/deadline.js'); },
  duel: function () { return import('./variants/duel.js'); },
  eyes: function () { return import('./variants/eyes.js'); },
  flowfield: function () { return import('./variants/flowfield.js'); },
  flyby: function () { return import('./variants/flyby.js'); },
  football: function () { return import('./variants/football.js'); },
  fractal: function () { return import('./variants/fractal.js'); },
  ghostrider: function () { return import('./variants/ghostrider.js'); },
  ghosts: function () { return import('./variants/ghosts.js'); },
  grass: function () { return import('./variants/grass.js'); },
  graveyard: function () { return import('./variants/graveyard.js'); },
  harmonograph: function () { return import('./variants/harmonograph.js'); },
  lander: function () { return import('./variants/lander.js'); },
  lighthouse: function () { return import('./variants/lighthouse.js'); },
  life: function () { return import('./variants/life.js'); },
  nightcity: function () { return import('./variants/nightcity.js'); },
  paddles: function () { return import('./variants/paddles.js'); },
  pongwars: function () { return import('./variants/pongwars.js'); },
  pumpkins: function () { return import('./variants/pumpkins.js'); },
  rocks: function () { return import('./variants/rocks.js'); },
  ships: function () { return import('./variants/ships.js'); },
  skyline: function () { return import('./variants/skyline.js'); },
  signalnoise: function () { return import('./variants/signalnoise.js'); },
  solari: function () { return import('./variants/solari.js'); },
  spider: function () { return import('./variants/spider.js'); },
  stix: function () { return import('./variants/stix.js'); },
  terrainflight: function () { return import('./variants/terrainflight.js'); },
  train: function () { return import('./variants/train.js'); },
  triangles: function () { return import('./variants/triangles.js'); },
  truchet: function () { return import('./variants/truchet.js'); },
  water: function () { return import('./variants/water.js'); },
  windfarm: function () { return import('./variants/windfarm.js'); }
};
